- name: Update nameserver into resolv.conf file on localhost
  gather_facts: false
  hosts: localhost
  vars:
    Car_Model: "BMW M3"
    Country_Name: USA
    title: "System Engineer"

  tasks:
    - name: Print my car model
      command: echo "My car's model is {{ Car_Model }}"

    - name: Print my country
      command: echo "I live in country {{ Country_Name }}"

    - name: Print my title
      command: echo "I work as {{ title }}"

